### ISSUE TITLE
Make footer menu consistent with header menus

### ISSUE THREAD

**Issue by rgilman** [ContextInstitute/bfcom#102]
I suggest that the footer menu get move out of the WP database and into the BFCom code, as we did with the top menu. I also suggest that we apply styling similar to the header menu, although with unique selectors. This would include centering it. 

@DavidScottBernstein, is this something you could take on?

**Comment by iangilman** [comment]
I assume we want it to be a little less conspicuous than the header menu, though, right?

**Comment by rgilman** [comment]
Sure. It could be smaller type or minimized in other ways.

**Comment by rgilman** [comment]
No need for icons but some custom selectors, at least for the group as a whole. I expect we may want to use [the CSS calc function](https://developer.mozilla.org/en-US/docs/Web/CSS/calc) to gradually shrink the type size and padding for smaller screens. We could also combine "Terms" and "Privacy" into one link for "Policies". The challenge may be to keep it on one line on the smallest screens.

If I were doing it, I'd start with the php work for desktop, get the desktop CSS working and then dive into responsive CSS. Note that we seem to be settling into media queries of `max-width: 767px` and `max-width: 374px`. Using calc within these allows for a smooth transition across a wide range. 

Font size is currently 16px. In keeping with Ian's comment, we might want to move that down to 14px on desktop and then bring it gradually down to 12px for a 300px viewport width. The padding is currently huge, effectively 32px between words. That works fine for desktop but also give us a lot of room to shrink. We just don't want to go so small that touch screens can't tell what's being aimed at.

**Comment by rgilman** [comment]
There is an example of using calc that mixes vw and px units starting at line 727 in assets > styles > style.css. It has worked so far in my testing. I was thinking we could do something similar for the footer.

**Comment by iangilman** [comment]
Yeah, I think it's more that there are certain exceptions where calc doesn't work when mixing units. I forget where I ran across that though.

**Comment by iangilman** [comment]
Thank you for updating the menu IDs to make them more meaningful!

I agree with @rgilman that we don't need active highlighting for footer items; I think most sites don't highlight footer items.

Looks like your editor config is working properly; removing trailing white space is one of the things it's supposed to do. I realize it adds a little noise to the pull request, but it's cleaner in the long run.

Happy 2019! :-)

**Comment by DavidScottBernstein** [comment]
@rgilman @iangilman Putting the copyright notice on the same line as the footer menu turned out to be a bit challenging. I finally put it at the bottom of bfc_bottom_nav() on line 326-328 of bfc-functions.pho in my last pull request. I also had to remove the inner-footer class in footer.php so the menu would center. 

Notice in bfc_functions.php, lines 326-329 I hardcoded "BFNet." since bloginfo('name') didn't seem to work and used "<p></p>" to generate a newline because the call to wp_footer() on line 16 of footer.php displays a status bar at the bottom of the window called Query Monitor that hides the bottom line of the page. Is this something we can remove?

Also, test out the responsive font resizing and let me know what you think. Feel free to adjust the styles to your liking.

I'll be teaching for a client and then at a conference next week and the week after. I'm home again the week of 2/11.

**Comment by rgilman** [comment]
@DavidScottBernstein, good to see this progress. I'm about to head into a four-day conference at Whidbey Institute and plan on getting back into BFCom when I get back. Should have more stuff for you to work on once you're home on the 11th.

**Comment by rgilman** [comment]
Also, Query Monitor is a debugging plugin that won't be part of the production site. You can deactivate it in your local dev if you aren't using it by going to Admin Dashboard > Plugins > Query Monitor.

**Comment by DavidScottBernstein** [comment]
@rgilman Great, thank you and enjoy the conference.

**Comment by iangilman** [comment]
@DavidScottBernstein Happy travels!

**Comment by rgilman** [comment]
Here are some notes on the changes I made building on @DavidScottBernstein good start:
- I moved the copyright notice to the front (left) of the line as seems to be the general convention
- I replaced the hard coded BFNet with `get_bloginfo('name')`. There is a convention in the WP world that `template_tag() = echo get_template_tag()`. If you need to output a variable, use `get_template_tag()`. If you are going right to something that will be displayed, use `template_tag()`.
- I tweaked the responsive font sizing and added responsive padding plus a few other styling tweaks.

Thanks again, @DavidScottBernstein, for all the work you put into this. I'm happy with what we've accomplished so will close this issue.
