### ISSUE TITLE
Move user-menu from Toolbar to user image in our header

### ISSUE THREAD

**Issue by rgilman** [ContextInstitute/bfcom#16]
The [Wordpress Toolbar](https://codex.wordpress.org/Toolbar) is a full-width strip, normally at the top of the screen, that includes links to many useful administrative functions. At the right end of the Toolbar is the user's avatar. Mousing over the avatar drops down a menu with many useful user-related links. BuddyPress integrates into this menu with BP-specific items.

I'd like to move the functionality of this drop-down menu to the user's avatar that we have in our header. I don't expect that we will have the Toolbar available for most users but I would like that menu to be available to all users.

**Comment by robertdavidwest** [comment]
I've started doing research on this issue. I believe that the two files we want to replicate code from are:
```
wp-includes/admin-bar.php
wp-includes/css/admin-bar.css
```
The former to create the menu and the latter to replicate the styling and hover functionality

**Comment by rgilman** [comment]
This is now superseded by PR #21, #31 and PR #34 so I'm closing this.
