### ISSUE TITLE
Make the local dev sites automatically https

### ISSUE THREAD

**Issue by rgilman** [ContextInstitute/bfcom#19]
The shared dev site on Digital Ocean is all https but that isn't currently translating into my local dev site. I'd like to make the local dev site automatically also https.

**Comment by iangilman** [comment]
I don't know that it's possible to set up HTTPS locally…

**Comment by rgilman** [comment]
The dev environment that I'm currently using in place of MAMP – [Local by Flywheel](https://local.getflywheel.com) – provides you with an local cert to do this. If I set _siteurl_ and _home_ to https://rcg.context.dev then the main pages of the site are automatically https but it looks like the forum pages aren't and other may not be as well.

It's probably not a big deal to have it https but I'm just trying to have the dev setup match what we will likely have in production. I'm just looking for an easy way to do this rather than hacking the database.

**Comment by rgilman** [comment]
On second look, it looks like the forum pages _are_ https so changing _siteurl_ and _home_ may be all that's needed.

I'm happy to leave it at that for now.

**Comment by iangilman** [comment]
Neat! I learn something new everyday. ;)
