### ISSUE TITLE
User avatar in upper right of header

### ISSUE THREAD

**Issue by iangilman** [ContextInstitute/bfcom#32]
... instead of the word "User".

@rgilman do you have any thoughts about how to get the URL for this image?

**Comment by rgilman** [comment]
`<a href="<?php bp_loggedin_user_link(); ?>"><?php bp_loggedin_user_avatar( 'type=full' ); ?></a>`

As I described in PR #16 .

**Comment by iangilman** [comment]
Beautiful! :)

**Comment by iangilman** [comment]
@DavidScottBernstein This is a smaller bite to take on before tackling #31.

**Comment by rgilman** [comment]
Apologies for getting wires crossed here. Take a look at PR #34 and see if this handles #32.

**Comment by DavidScottBernstein** [comment]
@iangilman I think I have this working locally. It shows the user icon that's hyperlinked to the user's page. Hovering over the user icon drops down a submenu pane that currently contains descriptions of what to add. Would you like me to check this in as is or build out the submenu items first?

**Comment by iangilman** [comment]
Fixed by #39.
