### ISSUE TITLE
BFN logo in header

### ISSUE THREAD

**Issue by iangilman** [ContextInstitute/bfcom#33]
... instead of the word "Logo".

@rgilman can you get us an image for this?

**Comment by rgilman** [comment]
We don't have a specific BFN logo. We are using the CI Logo. Attached is a zipped svg.
[Logo9b.svg.zip](https://github.com/ContextInstitute/bfcom/files/2416149/Logo9b.svg.zip)

**Comment by iangilman** [comment]
Great!

**Comment by rgilman** [comment]
This would be a good quick task after I get my recent code clean-up #37 and header recode #38 merged.

**Comment by iangilman** [comment]
Fixed by #40.
