### ISSUE TITLE
conform our existing code to our standards

### ISSUE THREAD

**Issue by rgilman** [ContextInstitute/bfcom#37]
We should at least do this for the files we have created or modified.

I did a comparison between BFCom and JointsWP. The issues I found are:

- parts/nav-bftop.php and parts/nav-bfsubmenu.php – the 'nav- ...' structure meshes with get_template_part() which is a WP function so we need to stay with that structure. We could rename the files nav-bfc_top.php and nav-bfc_submenu.php. I'm using underscores so the part after nav- gets treated as a block. The code in the files should also be conformed with our standards.
- header.php contains a 'get_template_part' reference to ('parts/nav', 'bftop') that would need to be updated to match the new file name.
- /assets/styles/style.css – any new code in here should be checked for coding standards.
- /functions/bfcom-fn.php – this should likely be changed to bfc-functions.php
- /functions.php contains a reference to bfcom-fn.php that would need to be updated.

I'm willing to do this clean-up.

**Comment by iangilman** [comment]
Sounds good.

**Comment by rgilman** [comment]
I've done all the file renaming and tested it to make sure it works. I'm going to hold off on the linting until I have better tools in place.

**Comment by rgilman** [comment]
Looks like [PHP_CodeSniffer rules (sniffs) to enforce WordPress coding conventions](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards) is what people use. It integrates with VS Code and I suspect with Atom as well.

**Comment by rgilman** [comment]
Commits [here] (https://github.com/ContextInstitute/bfcom/commit/e5c2bac5ef619813303a25cc0588387d0770489e) and [here](https://github.com/ContextInstitute/bfcom/commit/12f0ac39dacf7466b0df9d6f55e05e14a9048222)

While this will be an on-going process, I'm closing this as an issue now.

**Comment by rgilman** [comment]
I agree it looks odd. I'll test `nav-bfc-submenu.php` locally. If there are now issues, I'd be happy to update.

**Comment by iangilman** [comment]
Cool :-)
