### ISSUE TITLE
header - recode with CSS grid

### ISSUE THREAD

**Issue by rgilman** [ContextInstitute/bfcom#38]
The header is currently structured using the Foundation grid system. I'd like us to be consistent in using CSS grid for our layout.

As learning resources I recommend you watch [this playlist](https://www.youtube.com/watch?v=ZXr5XR7XOjo&list=PLNHKFtMjaNvHQ55HQE3Am_iIWCc7sSsYt) (that uses Pinegrow but the concepts transcend the software) and explore [A Complete Guide to Grid](https://css-tricks.com/snippets/css/complete-guide-grid/). There are many other learning resources for CSS grid a quick google search away.

**Comment by iangilman** [comment]
Go for it! 

My apprentice, Sean, suggests https://css-grid.coffeecup.com/ as an interesting CSS Grid tool.

**Comment by rgilman** [comment]
I've got this sorted out locally but I'd like to wait for the merging of PR #36 before going further.

**Comment by rgilman** [comment]
Thank Sean for the reference to https://css-grid.coffeecup.com/ . The CSS Grid tool looks like a nice resource. I prefer [Pinegrow](https://pinegrow.com), which has an equivalent CSS Grid tool (AFAIK - I haven't done a detailed comparison) plus a full toolset for all the other aspects of frontend development. Then again, it's not free. I used Pinegrow for this recode.

**Comment by rgilman** [comment]
Commits [here](https://github.com/ContextInstitute/bfcom/commit/6741a5b8bbb9dea60f026c7bb78b5e3bf2aa4e98) and [here](https://github.com/ContextInstitute/bfcom/commit/75a7c58d57fb1f006fff62ba34b581baa23114c7).

Closing this as an issue.

**Comment by iangilman** [comment]
I'm confused about nav-bfc_top.php… Where did it come from, and what happened to the old version of the header? How is this new one hooked in?

**Comment by rgilman** [comment]
The new one, by whatever name, is hooked in in the same places as the old one - header.php.

**Comment by iangilman** [comment]
I see. I just went through the commits in the picture is clearer now. Another good reason for  using a pull request next time!

**Comment by rgilman** [comment]
Point well taken about using a PR, which was my intention but in my rush I clicked the wrong branch.

**Comment by iangilman** [comment]
No worries. If you're up for changing the name to nav-bfc-top.php (and it doesn't cause any problems), please do so and then work can continue on that file.
