### ISSUE TITLE
topic page - page title and thread title

### ISSUE THREAD

**Issue by rgilman** [ContextInstitute/bfcom#50]
Here's what it looks like now:

![screen shot 2018-10-02 at 8 52 26 am](https://user-images.githubusercontent.com/615052/46360596-a38d4e00-c620-11e8-95d3-e4a1b99dfefb.png)

**Page title**
BP uses the group name as the page title throughout the group and styles it with an H1. That makes it way too big for it's appropriate place in the visual hierarchy. I would like to see it the same size as the menu text in the header. The user needs only a small reminder of what group this topic is in.

I'm seeing a couple of ways to approach this styling change; there may well be others.

1. We could use targeted selectors to redefine H1 in that location.
2. We could change the template. The html is in parts/loop-page.php, which is unfortunately a site-wide template. It is called from page.php which is also site wide. We could modify loop-page with a test that would allow it to be context sensitive. 

I suspect that in the long run the second approach is more robust but it may have more of an initial learning curve since it will require some PHP work and use of BP and bp-nouveau functions.

**Thread title**
From a visual hierarchy perspective, I feel this should be the largest type on the page. It's current size is likely fine, which is fortunate since it's generated directly by the bbPress plugin rather than through a template. See bbpress/includes/extend/buddypress/groups.php line 807 for bbp_topic_title().

**Spacing**
With the page title smaller, this could be tightened up.

How does all that sound to you?

**Comment by iangilman** [comment]
Sounds good. As for what to do about the H1, one angle is to think about the semantics. Semantically you should just have a single H1 per page, and it should be more or less the thing that describes the page as a whole. A popular recommendation in CSS circles is not to use things like H1 for styling at all, but just for their semantic meaning. Given that, would you say we are using the right H1 here?

**Comment by rgilman** [comment]
The page title identifies _the whole section of pages for the group_. It's like a breadcrumb. The thread title identifies/describes the page as whole.

**Comment by iangilman** [comment]
Yeah, makes sense. In which case semantically the thread title should be the H1 (regardless of how it's styled).

That said, it may make sense not to try to dig that deeply into the template code at first, so just restyling the H1 conditionally to this page might be a good start.

**Comment by rgilman** [comment]
Your call on the pace. :-)
