### ISSUE TITLE
topic page - post framing

### ISSUE THREAD

**Issue by rgilman** [ContextInstitute/bfcom#51]
At the moment, posts are set off from each other by a subtle alternation of background grey. That divides posters into two camps. I'd rather use a grey dividing line between posts (like in our current forum). I assume this could be done with some combination of top and/or bottom borders.

**Comment by DavidScottBernstein** [comment]
@iangilman, I have a question on #51

The light grey background color actually appears on every other post. The class bp_group has either odd or even selectors that indicates if the light grey background should show up for the post if odd or not if even.

If I can override the background color for the odd class and it should remove the shading. Once again it's the nesting of selectors that's causing me some confusion. 

The inspector window reads:
#bbpress-forums div.odd, 
#bbpress-forums ul.odd {
  background-color: #fbfbfb;
}

This is in a div with classes: bp_group, odd, etc., which is in an li with the class: bbp-body, in a ul with the id topic-98-replies, in a div with the id: bbpress-forums. 

I want to add to style.css:

<the right selector> odd {
  background-color: #ffffff;
}

What is the process to determine the right selector? Sorry, I guess I'm still missing some key concepts.

David.

**Comment by iangilman** [comment]
That looks good. I think the process of finding the right selector is often trial and error. You could try the most simple selector (`.odd`) and see if it works. If it doesn't, you have to get more specific by adding further selectors up the chain. The other thing to consider is whether a simple selector is too general... Perhaps `.odd` will affect other things we don't want to change. Limiting it with `#bbpress-forums` seems like a good protection against that.
