### ISSUE TITLE
Add border radius to user image

### ISSUE THREAD

**Issue by rgilman** [ContextInstitute/bfcom#73]
Let's soften the user image in the upper right of the header like we've done with the forum post avatars. That image is a bit smaller so maybe a radius of 8px.

**Comment by DavidScottBernstein** [comment]
@rgilman @iangilman I added a border radius to the user profile image in the upper right corner of the page, the post image and the member's profile image. These are the three avatar images I'm aware of on the site. Let me know if there're others. I thought the images looked best with a slightly larger border radius than suggested (10px, 12px, 16px). Let me know if you'd prefer it to be different.

**Comment by iangilman** [comment]
Looks good to me! Thank you for sharing the screenshots :)
