### ISSUE TITLE
Remove profile link from user image

### ISSUE THREAD

**Issue by rgilman** [ContextInstitute/bfcom#74]
Now that we have the dropdown panel attached to the user image in the upper right of the header, we don't need to link the image directly to anything. The link also makes the dropdown panel unusable on a touch device.

I'll just do this.

**Comment by DavidScottBernstein** [comment]
@rgilman Yes, I noticed this as well. Thank you for fixing it.

**Comment by rgilman** [comment]
Fixed in PR #75
