### ISSUE TITLE
Icon-only top nav not stable at mobile screen size

### ISSUE THREAD

**Issue by rgilman** [ContextInstitute/bfcom#76]
As I test the site at smaller screen sizes I'm finding that the top nav often reverts to words rather than icons when I move around the site. I don't have a sense of pattern yet although I can usually get the top nav to go back to icons only by switching the device from portrait to landscape and back again.

**Comment by iangilman** [comment]
@DavidScottBernstein Can you investigate? Note that your desktop browser developer tools have tools for simulating mobile browsers.
