### ISSUE TITLE
Replace joints_top_nav() with our own function for the top nav

### ISSUE THREAD

**Issue by rgilman** [ContextInstitute/bfcom#83]
I feel we need to get more control over the top nav:
- We need to indicate which section of the site the user is in via highlighting the top menu item even when the actual page is deeper in the hierarchy. This means a more sophisticated method for adding the `selected` class.
- I think it might be better (as we did with the forum topic admin action icons) to add the icons directly rather than depending on background images. I expect this will help us deal with #76.
- As @DavidScottBernstein said at one point, the current CSS that's tied to things like `.menu-item-167` is fragile. I'm already find this to be an issue with the Search menu item.
- As @iangilman said at one point, good to reduce our dependence on the database and changes that need to be made via the WP admin dashboard. We don't need that degree of user customizability. This will be especially helpful when we move to a multisite implementation. We don't want to, and we don't want others to have to, mess with adding those menu items via the WP admin dashboard for each site.

If we create our own function to replace `joints_top_nav()` in `nav-bfc-top.php`, we should be able to accomplish all of the above.

@DavidScottBernstein, I'm wondering if this might be something of interest now that you are moving up the PHP learning curve. I'd be happy to help with specifics. It doesn't need to be done right away. I just want to get it into the backlog.

**Comment by iangilman** [comment]
Sounds good, and I agree it sounds like a good task for @DavidScottBernstein. David, I leave it to you to figure out the sequencing of this and the other tasks.

**Comment by DavidScottBernstein** [comment]
Yes, this is something I’d like to get into, but I will need some guidance. @rgilman, can we zoom and discuss approaches? I’m out today (11/6). I’m available at noon tomorrow or at 10 am Thursday or Friday.

**Comment by rgilman** [comment]
@DavidScottBernstein great! Let's do noon tomorrow (Wednesday). I'll send you the zoom link via Slack.

**Comment by DavidScottBernstein** [comment]
Very good, I'm looking forward to it.
