### ISSUE TITLE
tooltip flip/flop on homepage

### ISSUE THREAD

**Issue by iangilman** [ContextInstitute/bfcom#9]
On the homepage if you hover over one of the links in the Recent Replies area, it puts up a tooltip. If your cursor is low enough, it touches the tooltip, which indicates to the browser that you're no longer over the link, so the tooltip goes away, so now you're over the link again in the tooltip comes back, etc.

<img width="355" alt="image" src="https://cloud.githubusercontent.com/assets/338989/26711787/bfe07a02-4717-11e7-8738-52bd30a8774e.png">

The fix should be as simple as adding `pointer-events: none` to the CSS for the tooltip.

**Comment by rgilman** [comment]
Applies to the old theme so I'm closing this.
